# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: clone diffusers
      uses: actions/checkout@v4
      with:
        repository: huggingface/diffusers
        path: diffusers
    - name: install diffusers
      run: |
         cd diffusers && python3 -m pip install .
    - name: pull lfs
      run: |
        cd tests/models-sd/SDXL/tiny-sdxl && git lfs pull
    - name: pull lfs
      run: |
        cd tests/models-sd/flux/tiny-flux-pipe && git lfs pull
    - name: symlink models directory
      run: |
        ln -s ../../../../models tests/models-full && 
        ln -s ../../../../models/ControlNet tests/models-cn
        ln -s ../../../../models/ControlNetXL tests/models-cn-xl
    - name: Test with pytest
      env:
        METAFUSION_MODELS_DIR: models-full
      run: |
        cd tests && python pipe_test.py
    - name: Test loader
      env:
        METAFUSION_MODELS_DIR: models-full
      run: |
        cd tests && python test_loader.py
    - name: Test worker 
      env:
        METAFUSION_MODELS_DIR: models-full
      run: |
        cd tests && python test_worker.py
    - name: Test worker flux
      env:
        METAFUSION_MODELS_DIR: models-full
      run: |
        cd tests && python test_worker_flux.py
